name: Container Release
description: Calls container:release via the Heroku CLI

inputs:
  api-key:
    description: Heroku's API Key
    required: true
  app-name:
    description: Heroku App Name
    required: true
  processes:
    description: The list of processes to release
    required: true

runs:
  using: composite
  steps:
    - name: Release
      shell: bash
      env:
        HEROKU_API_KEY: ${{ inputs.api-key }}
      run: heroku container:release -a ${{ inputs.app-name }} ${{ inputs.processes }}
