name: Shared Deploy
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
        description: "Heroku app name to deploy to"
      processes:
        required: true
        type: string
        description: "Space-separated list of processes to deploy (e.g., 'web worker release')"
    secrets:
      HEROKU_API_KEY:
        required: true
      CR_UN:
        required: true
      CR_PAT:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: wedgworth/actions/.github/actions/setup-docker@main
        with:
          cr-username: ${{ secrets.CR_UN }}
          cr-token: ${{ secrets.CR_PAT }}

      - name: Setup Heroku
        uses: wedgworth/actions/.github/actions/setup-heroku@main
        with:
            api-key: ${{ secrets.HEROKU_API_KEY }}

      - name: Push All Processes
        run: heroku container:push -a ${{ inputs.app-name }} ${{ inputs.processes }} -R --arg VERSION=main,GITHUB_SHA=${{ github.sha }}
        working-directory: ./deploy

      - name: Release
        run: heroku container:release -a ${{ inputs.app-name }} ${{ inputs.processes }} -v