name: Shared Release
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
        description: "Heroku app name to deploy to"
      processes:
        required: true
        type: string
        description: "Space-separated list of processes to deploy (e.g., 'web worker release')"
    secrets:
      HEROKU_EMAIL:
        required: true
      HEROKU_API_KEY:
        required: true
      CR_UN:
        required: true
      CR_PAT:
        required: true

jobs:
  promote-tag:
    name: Production Deploy
    runs-on: ubuntu-24.04
    env:
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Heroku
        uses: wedgworth/actions/.github/actions/setup-heroku@v0.5.0
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}

      - name: Setup Docker
        uses: wedgworth/actions/.github/actions/setup-docker@v0.5.0
        with:
          cr-username: ${{ secrets.CR_UN }}
          cr-token: ${{ secrets.CR_PAT }}

      - name: Pull Latest Image
        run: docker pull ghcr.io/${{ github.repository }}:main'

      - name: Extract Tags
        uses: wedgworth/actions/.github/actions/docker-tags@v0.5.0
        id: meta
        with:
          tags: type=semver,pattern={{ raw }}

      - name: Tag Latest Image
        run: |
          docker tag ghcr.io/${{ github.repository }}:main ${{ steps.meta.outputs.tags }}
          docker tag ghcr.io/${{ github.repository }}:main ghcr.io/${{ github.repository }}:latest
          for process in ${{ inputs.processes }}; do
            docker tag ${{ steps.meta.outputs.tags }} registry.heroku.com/${{ inputs.app-name }}/$process
          done
          docker push ${{ steps.meta.outputs.tags }}
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Push Tagged Image to Heroku
        run: heroku container:push ${{ inputs.processes }} -R -a ${{ inputs.app-name }} --arg VERSION=$GITHUB_REF_NAME
        working-directory: ./deploy

      - name: Heroku Release
        run: heroku container:release ${{ inputs.processes }} -a ${{ inputs.app-name }}
